# Homebrew formula for Icebox — Rust TUI Kanban Board with AI Sidebar
#
# Install:  brew tap SteelCrab/tap && brew install icebox
# Upgrade:  brew upgrade icebox
#
# Auto-generated by GitHub Actions in SteelCrab/icebox on every v* tag push.

class Icebox < Formula
  desc "Rust TUI Kanban Board with AI Sidebar"
  homepage "https://github.com/SteelCrab/icebox"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/SteelCrab/icebox/releases/download/v0.5.3/icebox-aarch64-apple-darwin.tar.gz"
      sha256 "da161946f89b34a9aec8f9a30c8a3ec681669f9bd631b72c38805325808a47af"
    end
  end

  def install
    bin.install "icebox"
  end

  test do
    assert_match "icebox", shell_output("#{bin}/icebox help")
  end
end
