# Homebrew formula for Icebox — Rust TUI Kanban Board with AI Sidebar
#
# Install:  brew tap SteelCrab/tap && brew install icebox
# Upgrade:  brew upgrade icebox
#
# Auto-generated by GitHub Actions in SteelCrab/icebox on every v* tag push.

class Icebox < Formula
  desc "Rust TUI Kanban Board with AI Sidebar"
  homepage "https://github.com/SteelCrab/icebox"
  version "0.4.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/SteelCrab/icebox/releases/download/v0.4.2/icebox-aarch64-apple-darwin.tar.gz"
      sha256 "551588f3fbd9be0e121ecafb0954a12a1e22df5447b9140a70b06d0ea6a0e46a"
    end
  end

  def install
    bin.install "icebox"
  end

  test do
    assert_match "icebox", shell_output("#{bin}/icebox help")
  end
end
