# Homebrew formula for Icebox — Rust TUI Kanban Board with AI Sidebar
#
# Install:  brew tap SteelCrab/tap && brew install icebox
# Upgrade:  brew upgrade icebox
#
# Auto-generated by GitHub Actions in SteelCrab/icebox on every v* tag push.

class Icebox < Formula
  desc "Rust TUI Kanban Board with AI Sidebar"
  homepage "https://github.com/SteelCrab/icebox"
  version "0.4.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/SteelCrab/icebox/releases/download/v0.4.1/icebox-aarch64-apple-darwin.tar.gz"
      sha256 "c6ff9e8c7c2d2f20d6c8e5ba964536d5f9bf42e871aea32fdbcd04f6d6e6bc2a"
    end
  end

  def install
    bin.install "icebox"
  end

  test do
    assert_match "icebox", shell_output("#{bin}/icebox help")
  end
end
